x-base: &base
  user: 1000:1000
  tty: true

x-rust: &rust
  build:
    context: ./docker/rust
  working_dir: /app
  environment:
    HOME: /tmp
    RUST_LOG: info,achiet=debug
    ACHIET_DB_URL: sqlite:app.db
    ACHIET_ADDR: 0.0.0.0:3399
    ACHIET_JWT_SECRET: secret
  volumes:
    - .:/app
    - ./.data/cargo:/usr/local/cargo/registry

services:
  rust:
    <<: [*base, *rust]
    command: cargo r

  wasm:
    <<: [*base, *rust]
    build:
      context: ./docker/wasm
    working_dir: /app/crates/wasm
    command: trunk serve
    ports:
      - 8080:8080

  node:
    <<: [*base]
    image: node:22-alpine
    working_dir: /app/web
    command: yarn run dev --host
    volumes:
      - .:/app
      - ./.data/yarn-cache:/home/node/.cache/yarn

  proxy:
    image: nginx:alpine
    ports:
      - 3399:80
    volumes:
      - ./docker/proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - rust
      - node

  firefox:
    <<: [*base]
    build:
      context: ./docker/firefox
    command: geckodriver --host 0.0.0.0 --allow-hosts firefox localhost
    environment:
      HOME: /tmp
      XDG_RUNTIME_DIR: /tmp
      WAYLAND_DISPLAY: $WAYLAND_DISPLAY
    volumes:
      - $XDG_RUNTIME_DIR/$WAYLAND_DISPLAY:/tmp/$WAYLAND_DISPLAY
    ports:
      - 4444:4444

  adminer:
    <<: [*base]
    image: adminer
    ports:
      - 8080:8080

  postgres:
    <<: [*base]
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data

  mysql:
    <<: [*base]
    image: mysql:8
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    volumes:
      - ./.data/mysql:/var/lib/mysql

  atlas:
    <<: [*base]
    image: arigaio/atlas
    working_dir: "/app"
    volumes:
      - ".:/app"
